### Домашнее задание «Библиотека numpy. Вычислительные задачи»



### Оглавление
  
1. [Задание 1](#task1)   
2. [Задание 2](#task2)  
3. [Задание 3](#task3)  
4. [Задание 4](#task4)  

###### 1. Задание 1 <a id='task1'></a>

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [6]:
import numpy as np
n = int(input('Введите N : '))
x = np.flipud(np.arange(0, n))
x

Введите N : 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

###### 2. Задание 2 <a id='task2'></a>

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [4]:
# Вариант 1
import numpy as np
n = int(input('Введите N : '))
x = np.diag(np.flipud(np.arange(0, n)))
sum_diag = x.trace()
print('\n', x, '\n\n', 'Сумма значений на диагонали :', sum_diag)

Введите N : 10

 [[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]] 

 Сумма значений на диагонали : 45


In [3]:
# Вариант 2
import numpy as np
n = int(input('Введите N : '))
x = np.diag(np.flipud(np.arange(0, n)))
sum_diag = sum(x[i][i] for i in range(n))
print('\n', x, '\n\n', 'Сумма значений на диагонали :', sum_diag)

Введите N : 10

 [[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]] 

 Сумма значений на диагонали : 45


###### 3. Задание 3 <a id='task3'></a>

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [5]:
import numpy as np
# Матрица (левая часть системы)
m1 = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
# Вектор (правая часть системы)
v1 = np.array([4, 12, -3])
rez_ = np.linalg.solve(m1, v1)
print('X =', rez_[0], '  Y =', rez_[1], ' Z =', rez_[2])

X = 0.4666666666666668   Y = 3.844444444444444  Z = -5.555555555555555


###### 4. Задание 4 <a id='task4'></a>

Имеется матрица (users_stats) покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем.

На сайт заходит очередной посетитель, о покупках которого известно следующее: (next_user_stats). 

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [40]:
import numpy as np


def cosine(a, b):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """

    # длины векторов
    aLength = np.linalg.norm(a)
    bLength = np.linalg.norm(b)

    return np.dot(a, b) / (aLength * bLength)


users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ],
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

max_ = [0, 0]
for user_id, user_st in enumerate(users_stats, start=1):
    cos = cosine(user_st, next_user_stats)
    if cos > max_[1]:
        max_[0] = user_id
        max_[1] = cos
print('Cамый похожий пользователь c User ID =',  max_[0])

Cамый похожий пользователь c User ID = 8
